global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]
  # this is unrelated. I used it for the rabbitmq testing
  - job_name: "rabbitmq"
    static_configs:
      - targets: ["host.docker.internal:15692"]
